### ISSUE TITLE
clamp doesn't handle NaN

### ISSUE THREAD

**Issue by cubiq** [Jamy-L/Pytorch-Contrast-Adaptive-Sharpening#1]
hey great implementation, thanks for sharing!

I noticed your comment in the code regarding `clamp(0, 1)`, just a heads-up as clamp doesn't seem to take care of NaN. In fact I get a lot of NaNs in the tensors :smile:

**Comment by Jamy-L** [comment]
Hi, thank you for your interest in this piece of code! You are definitely right, for dark areas of value 0 the code divided 0 by 0 which caused NaNs. This shoud be fixed now, please let me know you still encounter the issue

**Comment by cubiq** [comment]
hey thanks for the super quick reply, I was just converting NaNs to 0 but adding epsilon is definitely smarter. thanks again for making this open source!
